### ISSUE TITLE
LB (mod_proxy_balancer, sticke session有り)の設定

### ISSUE THREAD

**Issue by ghost** [a1153tm/LocialS#23]
Apache + mod_proxy_balancerを使いLBサーバx2を構築する

[終了条件]
ロードバランシングできていることをAPPサーバx2で確認する

**Comment by a1140an** [comment]
・APPサーバ1,2 (Kate, Lucy)へロードバランシングできていることを確認する。

・Cookieの中身によって、APPサーバ1,2へ振り分けられることを確認する。
例：
    Cookie: ROUTEID=.1\r\nならKateへ
    Cookie: ROUTEID=.2\r\nならLucyへ

参考：
http://httpd.apache.org/docs/2.2/ja/mod/mod_proxy_balancer.html

**Comment by a1140an** [comment]
HTTPリクエストがどこまで届いているか、トラブルシューティングが必要な時のために

http://avenueq.tachibanakikaku.com/ => プロキシのローカルコンテンツを返す
http://avenueq.tachibanakikaku.com/locials =>　バックエンドのAPPサーバへ転送

とした。特に問題ないようなのでクローズ。
