### ISSUE TITLE
APサーバのmemcached設定

### ISSUE THREAD

**Issue by ghost** [a1153tm/LocialS#24]
memachedをAPサーバにインストールし、セッション保存にmemcachedを利用する設定を行う

[終了条件]
アプリケーションがmemcachedを利用して動いている途中に断線させ、
セッションを利用する処理が継続できること。

**Comment by a1140an** [comment]
インストールと簡単な動作確認は済

$ telnet localhost 11211
set city 0 0 5  
tokyo
STORED
get city
VALUE city 0 5
tokyo
END
quit

**Comment by ghost** [comment]
great!

**Comment by a1140an** [comment]
作業完了
