### ISSUE TITLE
DBクラスタの設計

### ISSUE THREAD

**Issue by ghost** [a1153tm/LocialS#27]
**PostgreSQL**を利用したDBクラスタの構成を考える

[終了条件]
- pgpool2の利用モードを決定する
- PostgreSQLの利用方法を検討する

**Comment by ghost** [comment]
下記も考慮してお願いします。
- PgPoolのインストール・設定
- DBx2 (PostgreSQL)のディスク同期方法

**Comment by a1140an** [comment]
手元の仮想マシンで以下のことを確認。サーバルームでも同様の作業を行えば作業完了するものと思われる。

[PgPool2]
・設定変更個所
    - /usr/local/etc/pgpool.conf
        - listen_address = IPアドレス
        - backend_host_name = PostgreSQL1のホスト名
        - secondary_backend_host_name = PostgreSQL2のホスト名
        - secondary_backend_port = PostgreSQL2のリスナー
        - replication_mode = true
        - load_balance_mode = true

```
- /usr/local/etc/pool_hba.conf
    #host    all         all         127.0.0.1/32          trust
    host    all         all         0.0.0.0/0          trust
    ※セキュリティ要件にあわせて調整が必要

- /etc/sysconfig/iptables
    - -A INPUT -m state --state NEW -m tcp -p tcp --dport 9999 -j ACCEPT
```

[PostgreSQL x 2]
・設定変更個所
    - /var/lib/pgsql/data/pg_hba.conf
        - PgPool2のpool_hba.confに同じ

```
- /var/lib/pgsql/data/postgresql.conf
    - listen_addresses = IPアドレス
    - port = 5432

- /etc/sysconfig/iptables
    - -A INPUT -m state --state NEW -m tcp -p tcp --dport 5432 -j ACCEPT
```

[動作確認]
PgPool2に対してSQL操作すると、バックエンド２台に対してレプリケーションされることを確認済

**Comment by ghost** [comment]
good.

pg_hba.confに関しては近日話しましょう

**Comment by a1140an** [comment]
作業完了。PostgreSQL x 2側でも同じデータベースができていることを確認済み。

[root@trekkie ~]# psql -h 192.168.30.21 -p 9999 -U postgres -l
                                              データベース一覧
        名前         |  所有者  | エンコーディング |  照合順序   | Ctype(変換演算子) |      アクセス権  
---------------------+----------+------------------+-------------+-------------------+-----------------------
 locials_development | locials  | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | 
 locials_production  | locials  | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | 
 locials_test        | locials  | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | 
 postgres            | postgres | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | 
 template0           | postgres | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | =c/postgres
                                                                                     : postgres=CTc/postgres
 template1           | postgres | UTF8             | ja_JP.UTF-8 | ja_JP.UTF-8       | =c/postgres
                                                                                     : postgres=CTc/postgres
(6 行)

[root@trekkie ~]#
