### ISSUE TITLE
アプリのSession Storeの変更

### ISSUE THREAD

**Issue by ghost** [a1153tm/LocialS#34]
memcachedを使うように変更する。インフラチームとの調整が必要

[参考]

http://awesomerails.wordpress.com/2011/08/23/rails-3-memcached-session-store/

http://devcenter.heroku.com/articles/memcache

**Comment by ghost** [comment]
https://github.com/mperham/dalli

ここを見るのが一番手っ取り早いけど。

**Comment by a1153tm** [comment]
とりえずローカルでは動くのを確認しました

**Comment by a1153tm** [comment]
サーバでの動作確認が必要。別issueを発行する
